name: Integration tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [33] # TODO: add more api levels to test
    env:
      MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
      OTP_TEST_USER_AUTH_TOKEN: ${{ secrets.OTP_TEST_USER_AUTH_TOKEN }}
      APP_API_KEY: ${{ secrets.APP_API_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v3

    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.api-level }}

    - name: Create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        arch: x86_64
        script: echo "Generated AVD snapshot for caching."

    - name: Run tests with screen recording
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        arch: x86_64
        script: |
          adb shell screenrecord /sdcard/screenrecord.mp4 & 
          RECORD_PID=$!
          ./gradlew connectedDebugAndroidTest || true
          adb shell kill $RECORD_PID
          adb pull /sdcard/screenrecord.mp4
          ls -l  # List files to verify screenrecord.mp4 exists

    - name: Upload screen recording
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screenrecord
        path: screenrecord.mp4
        if-no-files-found: warn

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/build/reports/androidTests/"
        if-no-files-found: warn
